### ISSUE TITLE
Any kind of draw by repetition in cheskers?

### ISSUE THREAD

**Issue by Discontinuum** [GlukKazan/DagazServer#25]
![изображение](https://user-images.githubusercontent.com/68666085/217945214-60c3d03e-568e-4804-a663-ee3e0f23907b.png)
In this position the only move is Kb2, the AI moves Bd4, the only answer is Kc1 and the AI moves Be3 but no way to finalize this game in some way

**Comment by GlukKazan** [comment]
it is completely in line with the rules of the game.
