### ISSUE TITLE
[Help] Can't start project

### ISSUE THREAD

**Issue by estaticfear** [GlukKazan/DagazServer#27]
Has any instruction to start this project on localhost
I have errors on **yarn start:dev**
node 14, node 18
![image](https://github.com/GlukKazan/DagazServer/assets/6220969/06dc522e-c183-40bf-a2b6-f8ba75f40c37)

Thanks

**Comment by GlukKazan** [comment]
Just checked, everything is assembled and starts normally
![0001](https://github.com/GlukKazan/DagazServer/assets/2989905/9725bd67-0196-4077-b6bc-1e57cce9a3b6)
![0002](https://github.com/GlukKazan/DagazServer/assets/2989905/08aef962-5677-4082-8e0e-2ef4c83bc494)

**Comment by estaticfear** [comment]
still can't run start:dev
What is nodejs version you are using?
Can you remove package-lock.json and re install?

**Comment by GlukKazan** [comment]
dev won't start either, some problem with Nest. It doesn't interfere with the server.

**Comment by GlukKazan** [comment]
![0001](https://github.com/GlukKazan/DagazServer/assets/2989905/09d48460-0364-4166-bd7c-5fc97f870969)
